export function validateInvoiceSubmission(input: {
  consumerName: string;
  categoryId: string;
  locationId: string;
  itemCount: number;
}) {
  if (!input.consumerName.trim()) return "Customer name is required.";
  if (!input.categoryId) return "Invoice category is required.";
  if (!input.locationId) return "Location is required.";
  if (input.itemCount === 0) return "At least one invoice item must be added.";
  return "";
}

export function buildInvoiceSubmissionPayload(input: any) {
  const selectedLocation = input.locationOptions.find(
    (option: any) => option.value === input.locationId,
  );
  const total = Number(input.amount);
  return {
    categoryId: Number(input.categoryId) || undefined,
    statusId: Number(input.statusId) || undefined,
    invoiceId: input.invoiceNum.trim() || undefined,
    invoiceNum: input.invoiceNum.trim() || undefined,
    invoiceDate: new Date(input.invoiceDate).toISOString(),
    dueDate: input.dueDate ? new Date(input.dueDate).toISOString() : undefined,
    invoiceLabel: input.invoiceLabel.trim() || undefined,
    referenceNo: input.referenceNo.trim() || undefined,
    consumerType: input.selectedConsumerOption?.consumerType || "NONE",
    consumerUid: input.consumerUid || undefined,
    consumerName: input.consumerName.trim(),
    consumerPhone: input.consumerPhone.trim() || undefined,
    billedToAddress: input.billedToAddress.trim() || undefined,
    notesForProvider: input.notesForProvider.trim() || undefined,
    notesForCustomer: input.notesForCustomer.trim() || undefined,
    termsConditions: input.termsConditions.trim() || undefined,
    description: input.notesForCustomer.trim() || undefined,
    netTotal: total,
    netTotalAfterDiscount: total,
    amountDue: total,
    locationUid: input.locationId || undefined,
    locationId: input.locationId,
    locationName:
      selectedLocation?.label ||
      input.currentLocation?.name ||
      input.currentLocation?.place ||
      undefined,
    partyType: "B2C",
    supplyType: "INTRA_STATE",
    autoGenerated: false,
    sourceService: "FINANCE_SERVICE",
    feature: "FINANCE",
    subFeature: "FINANCE",
    featureModule: "FINANCE_INVOICE",
    detailList: input.items.map((item: any) => ({
      uid: item.detailUid || undefined,
      itemUid: item.itemUid || undefined,
      itemName: item.name,
      itemType: item.itemType,
      itemNature: "SINGLE_ITEM",
      quantity: item.qty,
      price: item.price,
      netTotal: item.price * item.qty,
      netTotalAfterDiscount: item.afterDiscount ?? item.price * item.qty,
      netRate: item.price,
      discountAmount: item.discountAmount ?? 0,
      sourceService: "FINANCE_SERVICE",
      feature: "FINANCE",
      subFeature: "FINANCE",
      featureModule: "FINANCE_INVOICE",
      locationUid: input.locationId || undefined,
      processedDate: new Date(item.date).toISOString(),
    })),
  };
}
